services:
  llm-snarf:
    build: .
    container_name: llmsnarf
    hostname: llmsnarf
#    image: alexakhbar/llmsnarf:latest
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - llmsnarf
    environment:
      - LLMSNARF_CONFIG=/app/config
    volumes:
      - ./config:/app/config
      - ./traces:/app/traces
      - ./logs:/app/logs
    depends_on:
      - openserp

  openserp:
    image: karust/openserp:latest
    container_name: openserp
    hostname: openserp
    command: serve -l
    ports:
      - "7000:7000"
    networks:
      - llmsnarf
    environment:
      - PORT=7000

networks:
  llmsnarf:
    driver: bridge
